Site emploi en PHP Laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Page d'acceuil
Route::get('/',function (){
    $offers = \App\Offer::all();
    $applications = \App\Application::all();
   return view('home',compact('offers','applications'));
});
Route::get('/needconnect',function (){
    return view('needconnect');
});
Route::get('/cannotapply',function (){
    return view('cannotapply');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Job')->prefix('job')->name('job.')->middleware('can:manage-users')->group(function (){
    Route::resource('/offers','OffersController',['except'=>'show'])->middleware('can:manage-users');
    Route::get('/offers/{offer}/candidats','ApplicationsController@CandidatsList')->middleware('can:manage-users');
});

Route::namespace('Job')->prefix('job')->name('job.')->group(function (){
    Route::resource('/applications','ApplicationsController',['except'=>'show']);
});


Route::get('/logged', 'LoggedController@index');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function (){
    Route::resource('/users','UsersController',['except'=>['show','create','store']])->middleware('can:manage-users');

});

Site emploi en PHP Laravel/app/Offer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    protected $fillable = ['poste','entreprise','ville_ent','departement',
        'type_contrat','desc','remuneration'];

    public function users(){
        return $this->belongsToMany('App\User');
    }
    public function applications(){
        return $this->belongsToMany('App\Application');
    }

}

Site emploi en PHP Laravel/app/Http/Controllers/Job/ApplicationsController.php
<?php

namespace App\Http\Controllers\Job;

use App\Application;
use App\Http\Controllers\Controller;
use App\Offer;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Gate;


class ApplicationsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $offers = Offer::all();
        $user = Auth::user();
        $applications =  Application::all();
        return view('job.applications.index')->with('applications',$applications)->with('user',$user)->with('offers',$offers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $offer = request('offer_id');
        $user = Auth::user()->getAuthIdentifier();
        if(Gate::denies('apply-users')){
            return redirect('/cannotapply');
        }

        $application = Application::create();
        $application-> users()->attach($user);
        $application-> offers()->attach($offer);



        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Application  $application
     * @return \Illuminate\Http\Response
     */
    public function show(Application $application)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Application  $application
     * @return \Illuminate\Http\Response
     */
    public function edit(Application $application)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Application  $application
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Application $application)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Application  $application
     * @return \Illuminate\Http\Response
     */
    public function destroy(Application $application)
    {
        //
    }
    public function CandidatsList(Offer $offer){
        $users = User::all();
        $applications =  Application::all();
        return view('job.offers.candidats')->with('offer',$offer)->with('users',$users)
            ->with('applications',$applications);

    }

}

Site emploi en PHP Laravel/app/Http/Controllers/Job/OffersController.php
<?php

namespace App\Http\Controllers\Job;

use App\Http\Controllers\Controller;
use App\Offer;
use App\User;
use App\Application;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class OffersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $offers = Offer::all();
        return view('job.offers.index')->with('offers',$offers)->with('user',$user);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('job.offers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,array(
            'poste' => 'required',
            'entreprise' => 'required',
            'ville_ent' => 'required',
            'departement' => 'required|min:2|max:3',
            'type_contrat' => 'required',
            'desc' => 'required',
            'remuneration' => 'required',
        ));
        $offer = Offer::create([
            'poste' => request('poste'),
            'entreprise' => request('entreprise'),
            'ville_ent' => request('ville_ent'),
            'departement' => request('departement'),
            'type_contrat' => request('type_contrat'),
            'desc' => request('desc'),
            'remuneration' => request('remuneration'),
        ]);
        $user = Auth::user()->getAuthIdentifier();
        $offer-> users()->attach($user);


        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function show(Offer $offer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function edit(Offer $offer)
    {
        return view('job.offers.edit')->with('offer',$offer);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Offer $offer)
    {
        $offer->poste = $request->poste;
        $offer->entreprise = $request->entreprise;
        $offer->ville_ent = $request->ville_ent;
        $offer->departement = $request->departement;
        $offer->desc = $request->desc;
        $offer->type_contrat = $request->type_contrat;
        $offer->remuneration = $request->remuneration;
        $offer->save();
        return redirect() -> route('job.offers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Offer $offer)
    {
        $offer->users()->detach();
        $offer->applications()->detach();
        $offer->delete();
        return redirect()->route('job.offers.index');
    }

}

Site emploi en PHP Laravel/app/Http/Controllers/OfferController.php
<?php

namespace App\Http\Controllers;

use App\Offer;
use App\User;
use Illuminate\Http\Request;

class OfferController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(){
        $offers = Offer::all();
        return (view('offer',compact('offers')));
    }
    public function store(){
        $offer = request()->validate([
            'poste' => 'required',
            'entreprise' => 'required',
            'ville_ent' => 'required',
            'departement' => 'required|min:2|max:3',
            'type_contrat' => 'required',
            'desc' => 'required',
            'remuneration' => 'required',
        ]);

        $user = User::select('id')->where('prenom','Super')->first();
        $offer-> users()->attach($user);

        Offer::create($offer);
        return redirect('/');
    }
}

Site emploi en PHP Laravel/resources/views/job/offers/candidats.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Liste des candidats de {{$offer->poste}}</div>
                    <div class="card-body" style="margin-left: 13px;">
                        <div class="row">
                            <ul class="list-group list-group-flush col" style="padding-right: 3px;">
                                <li class="list-group-item active">Nom</li>
                                @foreach($applications as $application)
                                    @if($application->offers()->get()->pluck('id')->contains($offer->id))
                                        <li class="list-group-item">{{implode($application->users()->get()->pluck('name')->toArray(),',')}}</li>
                                    @endif
                                @endforeach
                            </ul>
                            <ul class="list-group list-group-flush col" style="padding-right: 3px;">
                                <li class="list-group-item active">Prénom</li>
                                @foreach($applications as $application)
                                    @if($application->offers()->get()->pluck('id')->contains($offer->id))

                                        <li class="list-group-item">{{implode($application->users()->get()->pluck('prenom')->toArray(),',')}}</li>
                                    @endif
                                @endforeach
                            </ul>
                            <ul class="list-group list-group-flush col" style="padding-right: 3px;">
                                <li class="list-group-item active">Email</li>
                                @foreach($applications as $application)
                                    @if($application->offers()->get()->pluck('id')->contains($offer->id))
                                        <li class="list-group-item">{{implode($application->users()->get()->pluck('email')->toArray(),'<br>')}}</li>
                                    @endif
                                @endforeach
                            </ul>
                            <ul class="list-group list-group-flush col">
                                <li class="list-group-item active">Date de la candidature</li>
                                @foreach($applications as $application)
                                    @if($application->offers()->get()->pluck('id')->contains($offer->id))
                                        <li class="list-group-item">{{$application->created_at}}</li>
                                    @endif
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

Site emploi en PHP Laravel/resources/views/job/offers/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1 style="text-align: center">Créer une offre d'emploi</h1><br>
    <div class="row justify-content-center">
        <form method="POST" action="{{route('job.offers.store')}}" class="offer-form">
            @csrf
            <div class="form-group">
                <label for="poste">Intitulé du poste</label>
                <input id="poste" type="text" class="form-control @error('poste') is-invalid @enderror" name="poste" value="{{ old('poste') }}" required>
                @error('poste')
                <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
                @enderror
            </div>
             <div class="form-group">
                <label for="entreprise">Entreprise</label>
                <input id="entreprise" type="text" class="form-control @error('entreprise') is-invalid @enderror" name="entreprise" value="{{ old('entreprise') }}" required>
                @error('entreprise')
                <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
                @enderror
            </div>
            <div class="form-row">
                <div class="form-group col-10">
                    <label for="ville_ent">Localisation</label>
                    <input id="ville_ent" type="text" class="form-control @error('ville_ent') is-invalid @enderror" name="ville_ent" value="{{ old('ville_ent') }}" placeholder="Ville" required>
                    @error('ville_ent')
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                    @enderror
                </div>
                <div class="form-group col-2">
                    <label for="departement">&nbsp;</label>
                    <input id="departement" type="text" class="form-control @error('departement') is-invalid @enderror" name="departement" value="{{ old('departement') }}" placeholder="Département" required>
                    @error('departement')
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                    @enderror
                </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label for="desc">Description du poste</label>
                    <textarea class="form-control" style="width: 750px" rows="10" id="desc" class="form-control @error('desc') is-invalid @enderror" name="desc" value="{{ old('desc') }}" required></textarea>
                    @error('desc')
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                    @enderror
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="type_contrat">Type de contrat</label>
                    <input class="form-control" type="text" id="type_contrat" class="form-control @error('type_contrat') is-invalid @enderror" name="type_contrat" value="{{ old('type_contrat') }}" required>
                    @error('type_contrat')
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                    @enderror
                </div>
                <div class="form-group col">
                    <label for="remuneration">Rémuneration</label>
                    <input class="form-control" type="text" id="remuneration" class="form-control @error('remuneration') is-invalid @enderror" name="remuneration" value="{{ old('remuneration') }}" required>
                    @error('remuneration')
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                    @enderror
                </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-primary btn-lg" style="margin-left: 315px">Créer l'offre</button>
                </div>
            </div>

        </form>
    </div>
</div>

@endsection

Site emploi en PHP Laravel/resources/views/job/offers/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Editer {{$offer->poste}}</div>
                    <div class="card-body">
                        <form method="POST" action="{{route('job.offers.update',$offer)}}">
                            @csrf
                            {{method_field('PUT')}}
                            <div class="form-group">
                                <label for="poste">Intitulé du poste</label>
                                <input id="poste" type="text" class="form-control @error('poste') is-invalid @enderror" name="poste" value="{{$offer->poste}}" required>
                                @error('poste')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="entreprise">Entreprise</label>
                                <input id="entreprise" type="text" class="form-control @error('entreprise') is-invalid @enderror" name="entreprise" value="{{$offer->entreprise}}" required>
                                @error('entreprise')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-row">
                                <div class="form-group col-10">
                                    <label for="ville_ent">Localisation</label>
                                    <input id="ville_ent" type="text" class="form-control @error('ville_ent') is-invalid @enderror" name="ville_ent" value="{{ $offer->ville_ent}}" placeholder="Ville" required>
                                    @error('ville_ent')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group col-2">
                                    <label for="departement">&nbsp;</label>
                                    <input id="departement" type="text" class="form-control @error('departement') is-invalid @enderror" name="departement" value="{{ $offer->departement}}" placeholder="Département" required>
                                    @error('departement')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group">
                                    <label for="desc">Description du poste</label>
                                    <textarea class="form-control" style="width: 692px" rows="10" id="desc" class="form-control @error('desc') is-invalid @enderror" name="desc" value="{{ $offer->desc }}" required>{{ $offer->desc }}</textarea>
                                    @error('desc')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col">
                                    <label for="type_contrat">Type de contrat</label>
                                    <input class="form-control" type="text" id="type_contrat" class="form-control @error('type_contrat') is-invalid @enderror" name="type_contrat" value="{{ $offer->type_contrat}}" required>
                                    @error('type_contrat')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group col">
                                    <label for="remuneration">Rémuneration</label>
                                    <input class="form-control" type="text" id="remuneration" class="form-control @error('remuneration') is-invalid @enderror" name="remuneration" value="{{ $offer->remuneration }}" required>
                                    @error('remuneration')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-outline-primary btn-lg" style="margin-left: 253px">Mettre à jour l'offre</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

Site emploi en PHP Laravel/resources/views/job/offers/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Vos offres</div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">Poste</th>
                                <th scope="col">Entreprise</th>
                                <th scope="col">Action</th>
                            </tr>
                            </thead>
                            <tbody>

                                @foreach($offers as $offer)
                                    @if($offer->users()->get()->pluck('id')->contains($user->id))
                                    <tr>
                                        <td>{{$offer->poste}}</td>
                                        <td>{{$offer->entreprise}}</td>
                                        <td>
                                            <a href="{{route('job.offers.edit',$offer->id)}}" ><button type="button" class="btn btn-primary float-left" style="margin-right: 3px;">Editer</button></a>
                                            <a href="{{route('job.',$offer->id)}}" ><button type="button" class="btn btn-success float-left" style="margin-right: 3px;">Candidats</button></a>
                                            <form action="{{route('job.offers.destroy',$offer)}}" method="POST" class="float-left" >
                                                @csrf
                                                {{method_field('DELETE')}}
                                                <button type="submit" class="btn btn-danger">Supprimer</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endif
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection