Site emploi en PHP Laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Page d'acceuil
Route::get('/',function (){
    $offers = \App\Offer::all();
    $applications = \App\Application::all();
   return view('home',compact('offers','applications'));
});
Route::get('/needconnect',function (){
    return view('needconnect');
});
Route::get('/cannotapply',function (){
    return view('cannotapply');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Job')->prefix('job')->name('job.')->middleware('can:manage-users')->group(function (){
    Route::resource('/offers','OffersController',['except'=>'show'])->middleware('can:manage-users');
    Route::get('/offers/{offer}/candidats','ApplicationsController@CandidatsList')->middleware('can:manage-users');
});

Route::namespace('Job')->prefix('job')->name('job.')->group(function (){
    Route::resource('/applications','ApplicationsController',['except'=>'show']);
});


Route::get('/logged', 'LoggedController@index');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function (){
    Route::resource('/users','UsersController',['except'=>['show','create','store']])->middleware('can:manage-users');

});

Site emploi en PHP Laravel/app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','prenom','civi','adresse','ville','codep','dateNaiss',

    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',

    ];
    public function getAgeAttribute() {
        $age = Carbon::parse($this->attributes['dateNaiss'])->age;
        return $age;
    }
    public function roles(){
        return $this->belongsToMany('App\Role');
    }
    public function offers(){
        return $this->belongsToMany('App\Offer');
    }
    public function applications(){
        return $this->belongsToMany('App\Application');
    }
    public function hasAnyRoles($roles){
        if($this->roles()->whereIn('name',$roles)->first()){
            return true;
        }
        return false;
    }
    public function hasRole($role){
        if($this->roles()->where('name',$role)->first()){
            return true;
        }
        return false;
    }

}

Site emploi en PHP Laravel/app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;
;

use App\Role;
use App\User;
use App\Offer;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.index')->with('users',$users);
    }






    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if(Gate::denies('edit-users')){
            return redirect()->route('admin.users.index');
        }
        $roles = Role::all();
        return view('admin.users.edit')->with([
           'user'=>$user,
           'roles'=>$roles,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->roles()->sync($request->roles);
        return redirect()->route('admin.users.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if(Gate::denies('delete-users')){
            return redirect(route('admin.users.index'));
        }
        $user->roles()->detach();
        $user->offers()->detach();
        $user->applications()->detach();


        $user->delete();
        return redirect()->route('admin.users.index');
    }
}

Site emploi en PHP Laravel/resources/views/admin/users/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Editer {{$user->prenom}} {{$user->name}}</div>
                    <div class="card-body">
                        <form method="POST" action="{{route('admin.users.update',$user)}}">
                            @csrf
                            {{method_field('PUT')}}
                            @foreach($roles as $role)
                                <div class="form-check">
                                    <input type="checkbox" name="roles[]" value="{{$role->id}}"
                                    @if($user->roles->pluck('id')->contains($role->id)) checked @endif>
                                    <label>{{$role->name}}</label>
                                </div>
                            @endforeach
                            <button type="submit" class="btn btn-outline-primary">Mettre à jour l'utilisateur</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

Site emploi en PHP Laravel/resources/views/admin/users/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Utilisateurs</div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">Prenom</th>
                                    <th scope="col">Nom</th>
                                    <th scope="col">email</th>
                                    <th scope="col">Type d'utilisateur</th>
                                    @can('edit-users')
                                    <th scope="col">Action</th>
                                        @endcan
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <td>{{$user->prenom}}</td>
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>{{implode(',',$user->roles()->get()->pluck('name')->toArray())}}</td>
                                        <td>
                                            @can('edit-users')
                                            <a href="{{route('admin.users.edit',$user->id)}}" ><button type="button" class="btn btn-primary float-left" style="margin-right: 3px;">Editer</button></a>
                                            @endcan
                                            @can('delete-users')
                                            <form action="{{route('admin.users.destroy',$user)}}" method="POST" class="float-left" >
                                                @csrf
                                                {{method_field('DELETE')}}
                                                <button type="submit" class="btn btn-danger">Supprimer</button>
                                            </form>
                                                @endcan
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                </div>
            </div>
        </div>
    </div>
@endsection