Site emploi en PHP Laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Page d'acceuil
Route::get('/',function (){
    $offers = \App\Offer::all();
    $applications = \App\Application::all();
   return view('home',compact('offers','applications'));
});
Route::get('/needconnect',function (){
    return view('needconnect');
});
Route::get('/cannotapply',function (){
    return view('cannotapply');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Job')->prefix('job')->name('job.')->middleware('can:manage-users')->group(function (){
    Route::resource('/offers','OffersController',['except'=>'show'])->middleware('can:manage-users');
    Route::get('/offers/{offer}/candidats','ApplicationsController@CandidatsList')->middleware('can:manage-users');
});

Route::namespace('Job')->prefix('job')->name('job.')->group(function (){
    Route::resource('/applications','ApplicationsController',['except'=>'show']);
});


Route::get('/logged', 'LoggedController@index');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function (){
    Route::resource('/users','UsersController',['except'=>['show','create','store']])->middleware('can:manage-users');

});

Site emploi en PHP Laravel/resources/views/cannotapply.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="alert alert-danger" role="alert">
                    Nous sommes désolés vous ne pouvez pas postuler à cette offre si vous n’êtes pas connectés en tant que candidat.
                   <br> Connecter vous ou enregistrez vous en cliquant sur le logo de connexion en haut à droite.

                </div>
            </div>
        </div>
    </div>


@endsection

Site emploi en PHP Laravel/resources/views/createoffer.blade.php
@extends('layouts)
@section('content')
    <div class="container">
        <h2>Creer une offre</h2>
    </div>


@endsection

Site emploi en PHP Laravel/resources/views/hello.blade.php
<h1>Hello From View</h1>
<form method="POST" action="/profile">
    @csrf
    <input type="text" name="name">
    <button>Valider</button>
</form>

Site emploi en PHP Laravel/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="wrapper">
        <div class="sidebar">
            <h2>Recherche</h2>
            <ul style="padding-inline-start: unset;">
                <li>
                    <input type="text" class="form-control" placeholder="&#xF002;" style="font-family:Nunito, sans-serif,FontAwesome">
                </li>
            </ul>
        </div>
    </div>
        <div class="main_content">
            <div class="row justify-content-center">
                @foreach($offers as $offer)
                    <div class="col-md-8 border-top">
                        <h3 class="annonce-title">{{$offer->poste}}</h3>
                        <h5 style="font-style: italic;">{{$offer->entreprise}} - {{$offer->ville_ent}} ({{$offer->departement}})</h5>
                        <h5 class="text-primary">{{$offer->type_contrat}}</h5>
                        <p>{{$offer->desc}}</p>
                        <p style="font-weight: bold">{{$offer->remuneration}}</p>
                        <form action="{{route('job.applications.store')}}" method="POST">
                            @csrf
                            <button type="submit" class="btn btn-primary btn-lg marge-bot" name="offer_id" value="{{$offer->id}}">Postuler</button>
                        </form>


                    </div>
                @endforeach
            </div>
        </div>

@endsection

Site emploi en PHP Laravel/resources/views/home_backup.blade.php
@extends('layouts.app')

@section('content')
    
<div class="container-fluid ">
    <div class="row justify-content-center">
        <div class="col-md-8 border-top">
            <h3 class="annonce-title">Intitulé du poste</h3>
            <h5 style="font-style: italic;">Entreprise - Localisation</h5>
            <h5 class="text-primary">Type de contrat</h5>
            <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
            <p style="font-weight: bold">Remuneration</p>
            <button type="button" class="btn btn-primary btn-lg marge-bot">Postuler</button>
        </div>
        <div class="col-md-8 border-top">
            <h3 class="annonce-title">Intitulé du poste</h3>
            <h5 style="font-style: italic;">Entreprise - Localisation</h5>
            <h5 class="text-primary">Type de contrat</h5>
            <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
            <p style="font-weight: bold">Remuneration</p>
            <button type="button" class="btn btn-primary btn-lg marge-bot">Postuler</button>
        </div>
        <div class="col-md-8 border-top">
            <h3 class="annonce-title">Intitulé du poste</h3>
            <h5 style="font-style: italic;">Entreprise - Localisation</h5>
            <h5 class="text-primary">Type de contrat</h5>
            <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
            <p style="font-weight: bold">Remuneration</p>
            <button type="button" class="btn btn-primary btn-lg marge-bot">Postuler</button>
        </div>
        <div class="col-md-8 border-top">
            <h3 class="annonce-title">Intitulé du poste</h3>
            <h5 style="font-style: italic;">Entreprise - Localisation</h5>
            <h5 class="text-primary">Type de contrat</h5>
            <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
            <p style="font-weight: bold">Remuneration</p>
            <button type="button" class="btn btn-primary btn-lg marge-bot">Postuler</button>
        </div>
        <div class="col-md-8 border-top">
            <h3 class="annonce-title">Intitulé du poste</h3>
            <h5 style="font-style: italic;">Entreprise - Localisation</h5>
            <h5 class="text-primary">Type de contrat</h5>
            <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
            <p style="font-weight: bold">Remuneration</p>
            <button type="button" class="btn btn-primary btn-lg marge-bot ">Postuler</button>
        </div>
    </div>
</div>
@endsection

Site emploi en PHP Laravel/resources/views/homepage.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{{ asset('css/all.css') }}" rel="stylesheet">
    <title>Paris Jobs</title>
</head>
<body>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
<!----------------------------------------------------------------------------------------------------------Navbar--------------------------------------------------------------------------------------------------------------------->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light" id="nav_1">
    <a class="navbar-brand" href="#">
        <img id="nav_logo" src="img/logo_parisJobs_black.png" width="106" height="40" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="http://localhost:63342/Projet_BACHELOR_Web/index.html">Mairie de Paris</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/service">Services</a>
            </li>
        </ul>
    </div>
    <a href="/login" class='login_mod'>
        <img id="login_logo" src="img/icon/icons8-signin-50_dark.png" width="auto" height="30" alt=""align="right">
    </a>
</nav>
<!----------------------------------------------------------------------------------------------------------Entête-------------------------------------------------------------------------------------------------------------------->

<div class="jumbotron" style=" background-image: url({{ URL::asset('img/back_jumbotron.jpg') }});">
    <h1 class="display-4" style="color: white">Bienvenue sur le site de la <br> mairie de Paris</h1><br><br>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>
<!----------------------------------------------------------------------------------------------------------Login Modal---------------------------------------------------------------------------------------------------------------->
<div id="login_modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>
<!----------------------------------------------------------------------------------------------------------Register Modal---------------------------------------------------------------------------------------------------------------->
<div id="register_modal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content" id="reg_content">
        </div>
    </div>
</div>
<!------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
<section></section>
<section></section>
<script type="text/javascript" src="{{ asset('js/script.js') }}"></script>

</body>
</html>

Site emploi en PHP Laravel/resources/views/logged.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                      Bonjour, {{ Auth::user()->civi }} {{ Auth::user()->prenom }} {{ Auth::user()->name }} vous êtes connectés.<br>
                        Vous habitez au {{ Auth::user()->adresse }} à {{ Auth::user()->ville }} {{ Auth::user()->codep }}.<br>
                        Vous avez {{Auth::user()->age}} ans
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Site emploi en PHP Laravel/resources/views/needconnect.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-danger" role="alert">
                    Vous devez être connectés pour accéder à cette page veuillez retourner à l'accueil en cliquant <a href="/">ici</a> ou
                    vous connectez en cliquant sur le logo de connexion en haut à droite de la barre de navigation.
                </div>
            </div>
        </div>
    </div>
@endsection